import json
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from agents import chat
import re
import random


def extract_from_tags(text, tag):
    if text is None:
        return None
    pattern = re.compile(f"<{tag}>(.*?)</{tag}>", re.DOTALL)
    match = pattern.search(text)
    if match:
        return match.group(1).strip()
    return None


def complete(prompt, reasoning_effort_or_thinking_budget="high"):
    response = chat(
        max_retry=1,
        prompt=prompt,
        model_name="msra-gpt-5",
        enable_search=False,
        enable_thinking=True,
        reasoning_effort_or_thinking_budget=reasoning_effort_or_thinking_budget,
        temperature=1.0,
        top_p=1.0,
    )
    if response is None:
        return None
    return response["value"]


def get_counts(question, answers):
    repeat_count = 0
    answer_count = len(answers)
    while True:
        if repeat_count >= 3:
            return None
        prompt = f"""
Below are a question and a list of answers ({answer_count} in total) generated by some models.
**Question:**
{question}

**Answers:**
        """.strip()

        for idx, answer in enumerate(answers):
            prompt += f"\n{idx + 1}. {answer}"

        prompt += "\n\n"
        prompt += f"""
**Your task:**
* Understand the question and iterate through the {answer_count} answers one by one.
* Then, extract and count the occurrences of all the distinct answers implied by the list above, considering the context of the question.
* Guidelines:
1) Meaning over wording: Treat answers as the same if they express the same meaning, even if phrased differently (e.g., paraphrases, synonyms, or format changes).
2) Ignore non-essential variations: Disregard grammar, spelling, capitalization, filler words (e.g., “I think,” “probably”), and any reasoning or justification. Focus only on the final answer content.
3) Trim to relevance: If an answer includes extra or irrelevant content, extract only the portion that directly addresses the question.
4) Handle "None" consistently: Group all "None" and other answers that express uncertainty, refusal, or lack of information (e.g., "I don't know", "cannot determine", or "insufficient information") under a single distinct category labeled using the string "None".
5) Output format:
- Present the final result in valid JSON, where each key is a distinct answer and each value is its count.
- Enclose the JSON output within <results> and </results> tags.
- Example output: <results> {{"A": 3, "B": 2, "C": 1, "None": 1}} </results>
        """.strip()

        response = complete(prompt)
        distinct_answers_counts = extract_from_tags(response, "results")
        try:
            results = json.loads(distinct_answers_counts)
            if sum(results.values()) > answer_count or sum(results.values()) < answer_count * 0.9:
                repeat_count += 1
                continue
            return results
        except Exception as e:
            print(f"Error: {e}")
            repeat_count += 1


if __name__ == "__main__":
    total_count = int(sys.argv[1])
    index = int(sys.argv[2])
    file_name = sys.argv[3]

    save_file = f"outputs/medmcqa/processed_results/{file_name}_counts.jsonl"
    idx_uuid_done = []
    if not os.path.exists(save_file):
        with open(save_file, "w") as f:
            pass
    else:
        with open(save_file, "r") as f:
            for line in f:
                item = json.loads(line.strip())
                idx = str(item["idx"])
                uuid = str(item["uuid"])
                idx_uuid = idx + "_" + uuid
                idx_uuid_done.append(idx_uuid)
    all_idx_uuid = set()
    with open(f"outputs/medmcqa/processed_results/{file_name}.jsonl", "r") as f:
        for line in f:
            item = json.loads(line.strip())
            idx = str(item["idx"])
            uuid = str(item["uuid"])
            idx_uuid = idx + "_" + uuid
            all_idx_uuid.add(idx_uuid)
    remaining_idx_uuid = all_idx_uuid - set(idx_uuid_done)
    remaining_idx_uuid = sorted(list(remaining_idx_uuid))
    remaining_idx_uuid = [remaining_idx_uuid[i::total_count] for i in range(total_count)]
    remaining_idx_uuid = remaining_idx_uuid[index]
    print(f"chunk {index} size: {len(remaining_idx_uuid)}")


    with open(f"outputs/medmcqa/processed_results/{file_name}.jsonl", "r") as f:
        idx_to_uuid_to_answers = {}
        idx_to_uuid_to_question = {}
        for line in f:
            item = json.loads(line.strip())
            idx = str(item["idx"])
            uuid = str(item["uuid"])
            question = item["question"]
            if idx + "_" + uuid not in remaining_idx_uuid:
                continue
            if idx not in idx_to_uuid_to_answers:
                idx_to_uuid_to_answers[idx] = {}
            if uuid not in idx_to_uuid_to_answers[idx]:
                idx_to_uuid_to_answers[idx][uuid] = []
            if idx not in idx_to_uuid_to_question:
                idx_to_uuid_to_question[idx] = {}
            if uuid not in idx_to_uuid_to_question[idx]:
                idx_to_uuid_to_question[idx][uuid] = question
            if item["final_answer"] is None:
                continue
            idx_to_uuid_to_answers[idx][uuid].append(item["final_answer"])

        for idx in idx_to_uuid_to_answers:
            for uuid in idx_to_uuid_to_answers[idx]:
                answers = idx_to_uuid_to_answers[idx][uuid]
                question = idx_to_uuid_to_question[idx][uuid]
                if "temp0.0" not in file_name:
                    results = get_counts(question, answers)
                else:
                    if len(answers) == 1:
                        results = {answers[0]: 1}
                    else:
                        results = None
                if results is None:
                    continue
                print(f"[{idx}] {uuid} {results}")
                with open(save_file, "a") as f:
                    f.write(json.dumps({
                        "idx": idx,
                        "uuid": uuid,
                        "answer_counts": results,
                        "question": question,
                    }) + "\n")