import os
import json
import argparse
import jsonlines
import pandas as pd
from tqdm import tqdm
from datasets import Dataset
from vllm import LLM, SamplingParams
from typing import Optional, List
import re
import time
from uuid import uuid4
import re
import sys


PROMPT = """
Below is a question and a response generated by a model.

**Question (within <question> </question> tags)**
<question>
{question}
</question>

**Response to the Question (within <response> </response> tags)**
<response>
{response}
</response>

**Your Task**
Carefully read the above response and extract the four reasoning steps from it.
Identify and copy verbatim the portions of the response corresponding to each of the following steps:
1. Step 1 — Question Interpretation & Knowledge Retrieval:
The part where the model interprets or restates the question, and recalls any relevant facts, concepts, or background information.
2. Step 2 — Hypothesis Generation / Analysis / Evaluation:
Any portion where the model proposes, considers, analyzes, or evaluates possible answers or solution paths.
3. Step 3 — Double Checking / Re-examination:
Any portion where the model revisits earlier ideas, checks its reasoning, corrects itself, or reassesses its proposed hypothesis.
4. Step 4 — Summarizing & Final Conclusion:
The part where the model summarizes key points, forms its final conclusion, or states the final answer.

Guidelines:
* Note that the four steps appear in order in the response. They have no overlap. Together, they should cover the entire response (in other words, do not omit any part of the response).
* Extract each step's text verbatim from the response. Do not add, remove, reword, or modify anything.
* Enclose each extracted portion in tags:
    <step-1> ... </step-1>
    <step-2> ... </step-2>
    <step-3> ... </step-3>
    <step-4> ... </step-4>
""".strip()


def extract_from_tags(text, tag):
    if text is None:
        return None
    pattern = re.compile(f"<{tag}>(.*?)</{tag}>", re.DOTALL)
    match = pattern.search(text)
    if match:
        return match.group(1).strip()
    return None


def remove_thinking_draft(text):
    if "</think>" in text:
        text = text.split("</think>")[-1].strip()
        if len(text) > 0:
            return text
    if "</seed:think>" in text:
        text = text.split("</seed:think>")[-1].strip()
        if len(text) > 0:
            return text
    return text


def load_dataset(file, tokenizer):
    file = os.path.join("/mnt/blob_output/v-dachengwen/LLM-Stability-v2/outputs/medmcqa", file)

    prompts = []
    questions = []
    original_responses = []
    inner_idxs = []
    uuids = []
    ground_truths = []
    idxs = []

    with open(file, "r") as f:
        for line in f:
            item = json.loads(line.strip())
            idx = item["idx"]
            question = item["prompt"]
            uuid = item["uuid"]
            ground_truth = item["ground_truth"]
            responses = item["responses"]
            for i, response in enumerate(responses):
                try:
                    thinking_draft = extract_from_tags(response, "think")
                    if thinking_draft is None:
                        thinking_draft = extract_from_tags(response, "seed:think")
                    if thinking_draft is None:
                        continue
                    raw_prompt = PROMPT.format(question=question, response=thinking_draft)
                    prompt = tokenizer.apply_chat_template([{"role": "user", "content": raw_prompt}], tokenize=False, add_generation_prompt=True)
                    prompt_len = len(tokenizer.encode(prompt))
                    if prompt_len > 10240:
                        continue
                    prompts.append(prompt)
                    questions.append(question)
                    original_responses.append(response)
                    ground_truths.append(ground_truth)
                    inner_idxs.append(i)
                    uuids.append(uuid)
                    idxs.append(idx)

                except Exception as e:
                    continue

            # if len(prompts) >= 200:
            #     break
    return prompts, questions, original_responses, ground_truths, inner_idxs, uuids, idxs


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_name", type=str, required=False, default="Qwen/Qwen3-30B-A3B-Thinking-2507")
    parser.add_argument("--tensor_parallel_size", type=int, required=False, default=8)
    parser.add_argument("--max_prompt_length", type=int, required=False, default=10240)
    parser.add_argument("--max_completion_length", type=int, required=False, default=10240)
    parser.add_argument("--temperature", type=float, required=False, default=0.6)
    parser.add_argument("--file_name", type=str, required=True)
    args = parser.parse_args()

    file_name = args.file_name + ".jsonl"
    all_files = os.listdir("/mnt/blob_output/v-dachengwen/LLM-Stability-v2/outputs/medmcqa")
    assert file_name in all_files

    save_dir = "/mnt/blob_output/v-dachengwen/LLM-Stability-v2/outputs/medmcqa/"
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    save_file = os.path.join(save_dir, file_name.replace(".jsonl", "_masks.jsonl"))

    if os.path.exists(save_file):
        print(f"Results already exist in [{save_file}], skipping ...")
        exit()

    llm = LLM(
        model=args.model_name,
        gpu_memory_utilization=0.8,
        max_model_len=args.max_prompt_length + args.max_completion_length,
        max_num_batched_tokens=args.max_prompt_length + args.max_completion_length,
        dtype="bfloat16",
        tensor_parallel_size=args.tensor_parallel_size,
        trust_remote_code=True,
    )

    prompts, questions, original_responses, ground_truths, inner_idxs, uuids, idxs = load_dataset(file_name, llm.get_tokenizer())

    print(f"Processing [{args.model_name}] on [{file_name}] ({len(prompts)} prompts) ...")
    print(f"Results will be saved to [{save_file}] ...")
    sampling_params = SamplingParams(
        n=1,
        temperature=args.temperature,
        top_p=0.95,
        max_tokens=args.max_completion_length,
    )
    outputs = llm.generate(prompts, sampling_params, use_tqdm=True)

    res = []
    for i in range(len(outputs)):
        assert len(outputs[i].outputs) == 1, f"Expected {1} outputs, but got {len(outputs[i].outputs)}"
        response = outputs[i].outputs[0].text.strip()
        step_1 = extract_from_tags(remove_thinking_draft(response), "step-1")
        step_2 = extract_from_tags(remove_thinking_draft(response), "step-2")
        step_3 = extract_from_tags(remove_thinking_draft(response), "step-3")
        step_4 = extract_from_tags(remove_thinking_draft(response), "step-4")
        res.append({
            "idx": idxs[i],
            "uuid": uuids[i],
            "inner_idx": inner_idxs[i],
            "question": questions[i],
            "original_response": original_responses[i],
            "step_1": step_1,
            "step_2": step_2,
            "step_3": step_3,
            "step_4": step_4,
            "ground_truth": ground_truths[i],
            "response": response,
        })

    # save to jsonl file
    with open(save_file, "a") as f:
        for item in res:
            f.write(json.dumps(item) + "\n")